spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/vredu?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: xp19940912


logging:
  file: pay.log
  level:
    com.xp.paytest: debug
